apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  source:
    repoURL: https://github.com/eitatech/deployments.git
    path: argocd/apps/kafka/resources
    targetRevision: main
    directory:
      include: "kafka-cluster.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  dependencies:
    - strimzi-operator
