apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  source:
    repoURL: https://github.com/eitatech/deployments.git
    path: argocd/apps/kafka/ingress
    targetRevision: main
    helm:
      valueFiles:
        - ../values/ingress-values.yaml
      parameters:
        - name: domain
          value: "localhost"  # Este valor pode ser sobrescrito ao criar a aplicação
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependencies:
    - kafka-cluster
