apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-rbac
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  source:
    repoURL: https://github.com/eitatech/deployments.git
    path: argocd/apps/vault
    targetRevision: main
    directory:
      include: rbac.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  dependencies:
    - vault-dev