apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/eitatech/deployments.git
    path: argocd/apps/vault
    targetRevision: main
    directory:
      include: "vault-application-dev.yaml,rbac-application.yaml,init-unseal-job-application.yaml"
      exclude: "rbac.yaml,init-unseal-job.yaml"
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true