apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Nome específico para o ambiente
  name: vault-app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    # Namespace específico para o ambiente, para isolamento
    namespace: vault
  
  # A fonte dos nossos manifestos é o nosso próprio repositório Git
  source:
    repoURL: https://github.com/eitatech/deployments.git
    # O path aponta para o diretório que contém os hooks e os values
    path: argocd/apps/vault 
    targetRevision: main

    # Configuração do Helm
    helm:
      # O nome do release no Kubernetes
      releaseName: vault
      
      # Especificar o chart remoto
      chart: vault
      repo: https://helm.releases.hashicorp.com
      
      # AQUI ESTÁ A LÓGICA DE SOBREPOSIÇÃO:
      # ArgoCD irá mesclar esses arquivos. 'dev.yaml' sobrescreve 'base.yaml'.
      valueFiles:
      - values/base.yaml
      - values/dev.yaml
      
      # Precisamos dizer ao ArgoCD onde encontrar o chart do Vault,
      # já que não está no nosso repositório.
      # Para isso, o repo Helm da HashiCorp deve ser adicionado ao ArgoCD.
      # (Se você já fez, não precisa fazer de novo)
      # $ argocd repo add https://helm.releases.hashicorp.com --type helm --name hashicorp
      #
      # (Esta parte é implícita se você usar um Chart.yaml local, mas para
      # usar um chart remoto com values locais, esta é a abordagem)

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true # Garante que o namespace 'vault' seja criado